# Generated by Django 4.1.3 on 2022-11-10 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timetracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
        migrations.AddField(
            model_name="timeframe",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timetracker.usersession",
            ),
        ),
        migrations.AddField(
            model_name="screenshot",
            name="time_frames",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="timetracker.timeframe"
            ),
        ),
    ]
