# Generated by Django 4.1.3 on 2022-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetracker", "0004_alter_timeframe_start_alter_usersession_start")
    ]

    operations = [
        migrations.AlterField(
            model_name="timeframe",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="session end time"
            ),
        ),
    ]
