# Generated by Django 4.1.3 on 2022-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("timetracker", "0005_alter_timeframe_end_alter_usersession_end")]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="current",
            field=models.BooleanField(default=False),
        )
    ]
