# Generated by Django 4.1.3 on 2022-11-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("timetracker", "0006_usersession_current")]

    operations = [
        migrations.AddField(
            model_name="timeframe",
            name="current",
            field=models.BooleanField(default=False),
        )
    ]
