# Generated by Django 4.1.3 on 2022-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("timetracker", "0007_timeframe_current")]

    operations = [
        migrations.RenameField(
            model_name="screenshot", old_name="time_frames", new_name="time_frame"
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="photo",
            field=models.ImageField(upload_to="media/screenshots"),
        ),
    ]
