# Generated by Django 4.1.3 on 2022-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetracker", "0008_rename_time_frames_screenshot_time_frame_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/screenshots"
            ),
        )
    ]
