# Generated by Django 4.1.3 on 2022-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("timetracker", "0009_alter_screenshot_photo")]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="screenshots"),
        )
    ]
